# Generated by Django 4.2.10 on 2024-03-04 23:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='brand')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='name')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='address')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='model')),
                ('serial', models.CharField(blank=True, max_length=50, null=True, verbose_name='serial')),
                ('imei', models.CharField(blank=True, max_length=50, null=True, verbose_name='imei')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='type')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='ReplacementPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='model')),
                ('price', models.PositiveSmallIntegerField()),
                ('delivery_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('date_release', models.DateField(default=datetime.date.today)),
                ('date_done', models.DateField()),
                ('contents', models.CharField(blank=True, max_length=255, null=True, verbose_name='contents')),
                ('bug', models.CharField(blank=True, max_length=255, null=True, verbose_name='bug')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='notes')),
                ('work_list', models.CharField(blank=True, max_length=255, null=True, verbose_name='actions')),
                ('points_achieved', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('device', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='api.device')),
            ],
        ),
    ]
