# Generated by Django 4.2.10 on 2024-03-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_brand_brand_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='replacement_parts',
        ),
        migrations.AddField(
            model_name='order',
            name='replacement_parts',
            field=models.ManyToManyField(blank=True, null=True, to='api.replacementpart'),
        ),
    ]
